source 'https://github.com/CocoaPods/Specs.git'

target 'MCUIImageAdvanced_Example', :exclusive => true do
  pod "MCUIImageAdvanced", :path => "../"
end

target 'MCUIImageAdvanced_Tests', :exclusive => true do
  pod "MCUIImageAdvanced", :path => "../"
end
