source 'https://cdn.cocoapods.org/'
source 'git@github.com:mirego/MCPodSpecs.git'

platform :ios, '8.0'

target 'MCUIImageAdvanced_Example' do
  pod 'MCUIImageAdvanced', :path => '../'

  target 'MCUIImageAdvanced_Tests' do
    inherit! :search_paths
  end
end
